# Configuração dos terrenos
terrenos:
  pequeno:
    tamanho: 10
    custo: 10000.0
  medio:
    tamanho: 20
    custo: 20000.0
  grande:
    tamanho: 30
    custo: 30000.0
# Mundos bloqueados, use [] para não bloquear nenhum
mundos_bloqueados:
  - spawn
  - nether
  - end
# Configuração de banco de dados, use 'false' para SQLite e 'true' para MySQL
MySQL: false
mysql:
  host: "localhost"
  port: "3306"
  database: "minecraft"
  username: "root"
  password: ""
