# Configuração dos terrenos
terrenos:
  pequeno:
    tamanho: 10
    custo: 100.0
  medio:
    tamanho: 20
    custo: 250.0
  grande:
    tamanho: 30
    custo: 500.0

# Configuração de banco de dados
MySQL: false
mysql:
  host: "localhost"
  port: "3306"
  database: "minecraft"
  username: "root"
  password: ""
