name: LIZTerrenos
version: '1.4'
main: br.com.henriplugins.LIZTerrenos
api-version: 1.19
author: LevImpZ
depend: [Vault]
commands:
  comprar:
    description: Comando para comprar terrenos.
    usage: /comprar <pequeno | medio | grande>
  confiar:
    description: Adiciona um jogador à lista de confiança.
    usage: /confiar <nick>
  desconfiar:
    description: Remove um jogador da lista de confiança.
    usage: /desconfiar <nick>
  terreno:
    description: Comando principal para gerenciamento de terrenos
    aliases: [terreno]
